language: python
sudo: false
python:
  - "2.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # setup networker in conda environment 
  - conda create -n networker python=2.7
  # setup coverage tools
  - conda install --yes -n networker coverage
  - conda install --yes -n networker coveralls
before_script:
  # cache the lib dir and activate the conda environment
  # - ldconfig "$HOME/miniconda/envs/networker/lib"
  - source activate networker
  - conda install --yes -c conda-forge --file requirements.txt
  - conda install --yes -c conda-forge -c sel networkplanner-metrics
  - find -name '*.py' | xargs sed -i 's/@jit/# @jit/'
script:
  - nosetests --with-coverage
after_success: coveralls
